# STIG Manager docker-compose orchestration

version: '3.7'

services:
  db:
    # image: mysql:8.0
    image: registry1.dso.mil/ironbank/opensource/mysql/mysql8 
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_USER=stigman
      - MYSQL_DATABASE=stigman
      - MYSQL_PASSWORD=stigmanpw
    # uncomment lines below to persist API data
    # volumes:
    #   - ./mysql-data:/var/lib/mysql

  api:
    image: nuwcdivnpt/stig-manager:latest
    environment:
      - STIGMAN_OIDC_PROVIDER=http://auth:8080/realms/stigman
      - STIGMAN_CLIENT_OIDC_PROVIDER=https://trinity.localdomain/kc/realms/stigman
      - STIGMAN_CLASSIFICATION=U
      - STIGMAN_DB_HOST=db
      - STIGMAN_DB_USER=stigman
      - STIGMAN_DB_PASSWORD=stigmanpw
      # uncomment line below to fetch current STIG library from DISA and import it
      # - STIGMAN_INIT_IMPORT_STIGS=true
    init: true
  auth:
    # image: quay.io/keycloak/keycloak:19.0.2
    image: registry1.dso.mil/ironbank/opensource/keycloak/keycloak:19.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Pa55w0rd
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://trinity.localdomain/kc/
      - KC_HOSTNAME_ADMIN_URL=https://trinity.localdomain/kc/
      - KC_SPI_X509CERT_LOOKUP_PROVIDER=nginx
      - KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT=SSL-CLIENT-CERT
      - KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CERT_CHAIN_PREFIX=useless
      - KC_SPI_X509CERT_LOOKUP_NGINX_CERTIFICATE_CHAIN_LENGTH=2
      - KC_SPI_TRUSTSTORE_FILE_FILE=/tmp/truststore.p12
      - KC_SPI_TRUSTSTORE_FILE_PASSWORD=password
    command: start --import-realm
    volumes:
      - ./certs/dod/dod-id-5.9.p12:/tmp/truststore.p12
      - ./kc/stigman_realm.json:/opt/keycloak/data/import/stigman_realm.json
      - ./kc/create-x509-user.jar:/opt/keycloak/providers/create-x509-user.jar
      # uncomment statement below to persist Keycloak data
      # - ./kc/h2:/opt/keycloak/data/h2
  nginx:
    # image: nginx:latest
    image: registry1.dso.mil/ironbank/opensource/nginx/nginx
    volumes:
      - ./nginx/nginx-api-kc.conf:/etc/nginx/nginx.conf
      - ./certs/trinity.localdomain/trinity.localdomain.crt:/etc/nginx/cert.pem
      - ./certs/trinity.localdomain/trinity.localdomain.key:/etc/nginx/privkey.pem
      - ./certs/dod/dod-id-5.9.pem:/etc/nginx/dod-id.pem
      - ./nginx/index.html:/usr/share/nginx/html/index.html
    # command: [nginx-debug, '-g', 'daemon off;']
    ports:
    - "443:443"

    